spring:
 application:
  name: platform-appmock
 session:
  store-type: redis
 redis:
  # Redis数据库索引（默认为0）
  database: 0
  host: 192.168.1.121
  port: 6379
#  timeout: 259200
  pool:
   # 连接池最大连接数（使用负值表示没有限制）
   max-active: 8
   # 连接池最大阻塞等待时间（使用负值表示没有限制）
   max-wait: -1
   # 连接池中的最大空闲连接
   max-idle: 8
   # 连接池中的最小空闲连接
   min-idle: 0
# datasource:
#  url: jdbc:mysql://192.168.1.121:3306/testingplatform?autoReconnect=true&useSSL=false&characterEncoding=utf-8
#  username: root
#  password: Imobpay123456!
#  driver-class-name: com.mysql.jdbc.Driver
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
 rabbitmq:
    host: 192.168.1.121
    port: 5672
    username: rabbitadmin
    password: 123456
management:
  security:
    enabled: false
#logging:
#  level:
#    ROOT: DEBUG